# To do
Nodes which have high median time spent and high degree  
Finding connector hubs  
Finding betweenness centrality  
Finding control nodes  
All the regions get synchronised

In [5]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [3]:
people_dict = {
    "weight": pd.Series([68, 83, 112], index=["alice", "bob", "charles"]),
    "birthyear": pd.Series([1984, 1985, 1992], index=["bob", "alice", "charles"], name="year"),
    "children": pd.Series([0, 3], index=["charles", "bob"]),
    "hobby": pd.Series(["Biking", "Dancing"], index=["alice", "bob"]),
}
people = pd.DataFrame(people_dict)
people

         weight  birthyear  children    hobby
alice        68       1985       NaN   Biking
bob          83       1984       3.0  Dancing
charles     112       1992       0.0      NaN

In [11]:

grades_array = np.array([[8, 8, 9], [10, 9, 9], [4, 8, 2], [9, 10, 10]])
grades = pd.DataFrame(grades_array, columns=["sep", "oct", "nov"], index=["alice", "bob", "charles", "darwin"])
final_grades=grades
final_grades

         sep  oct  nov
alice      8    8    9
bob       10    9    9
charles    4    8    2
darwin     9   10   10

In [12]:
final_grades["hobby"] = ["Biking", "Dancing", np.nan,"Dancing"]
final_grades

         sep  oct  nov    hobby
alice      8    8    9   Biking
bob       10    9    9  Dancing
charles    4    8    2      NaN
darwin     9   10   10  Dancing

In [16]:
final_grades.fillna("Biking")

         sep  oct  nov    hobby
alice      8    8    9   Biking
bob       10    9    9  Dancing
charles    4    8    2   Biking
darwin     9   10   10  Dancing

In [23]:
grouped_grades = final_grades.groupby("hobby")
grouped_grades.info()

AttributeError: 'DataFrameGroupBy' object has no attribute 'info'