# Extract node community using local order data  
1. Extract node communities data

In [1]:
%reload_ext autoreload
%autoreload 2

from tes.data_ingestion import DataRead
from tes.analysis import AnalysisFunc

Create object to read data

In [2]:
nc_ext = DataRead()
analyse = AnalysisFunc()

Store local order data in dataframe

In [3]:
df_loc = nc_ext.data_read_bz2("raw/check_control/loc_200_4.bz2")

In [5]:
df_itr=nc_ext.data_read_bz2("raw/FN/itr_600.bz2")

In [6]:
l=analyse.compute_param(df_itr,0.05)

Number of transitions / 100 iteration [0, 79, 139]
Number of transition [1, 3, 4, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 23, 24, 26, 28, 29, 30, 32, 33, 34, 35, 36, 38, 39, 40, 41, 42, 44, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 59, 61, 63, 64, 65, 66, 67, 68, 69, 74, 75, 77, 79, 80, 81, 82, 83, 86, 90, 91, 93, 94, 95, 97, 98, 100, 101, 102, 107, 109, 112, 113, 114, 117, 120, 121, 122, 131, 133, 135, 136, 137, 139, 140, 144, 146, 148, 149, 151, 152, 153, 154, 156, 162, 163, 164, 167, 168, 170, 173, 174, 176, 177, 178, 182, 183, 184, 186, 187, 188, 190, 191, 192, 194, 195, 196, 197, 198]
Number of transition with more than one transition or a fall back [16, 17, 19, 20, 36, 50, 51, 55, 61, 65, 67, 69, 77, 80, 86, 94, 97, 98, 107, 109, 112, 113, 117, 121, 140, 148, 177, 178, 187, 191]

#### 1. Extract node communities data

In [ ]:
threshold = 0.5
nc_ext.ext_node_community(df_loc, threshold, "raw/check_control/nc_200_4.bz2")

../../data/connectivity_matrix/mb_communities.npz already exists
DataUtils initialized

/home/jupyter-nimish/srg-tes-epilepsy-models/analysis/tes/tES_Adaptive.py:141: RuntimeWarning: divide by zero encountered in divide
  K_ = 1 / self.K

Cluster tracking complete!
1 Cluster track complete for transition in iteration 0
Cluster tracking complete!
2 Cluster track complete for transition in iteration 2
Cluster tracking complete!
3 Cluster track complete for transition in iteration 4
Cluster tracking complete!
4 Cluster track complete for transition in iteration 9
Cluster tracking complete!
5 Cluster track complete for transition in iteration 10
Cluster tracking complete!
6 Cluster track complete for transition in iteration 12
Cluster tracking complete!
7 Cluster track complete for transition in iteration 15
Cluster tracking complete!
8 Cluster track complete for transition in iteration 16
Cluster tracking complete!
9 Cluster track complete for transition in iteration 19
Cluster tracking complete!
10 Cluster track complete for transition in iteration 20
Cluster tracking complete!
11 Cluster track complete for transition in iteration 20
Cluster tracking complete!
12 Cluster track complete for transition in iteration 21
Cluster tracking complete!
13 Cluster track complete for transition in iteration 22
Cluster tracking complete!
14 Cluster track complete for transition in iteration 26
Cluster tracking complete!
15 Cluster track complete for transition in iteration 29
Cluster tracking complete!
16 Cluster track complete for transition in iteration 29
Cluster tracking complete!
17 Cluster track complete for transition in iteration 31
Cluster tracking complete!
18 Cluster track complete for transition in iteration 32
Cluster tracking complete!
19 Cluster track complete for transition in iteration 34
Cluster tracking complete!
20 Cluster track complete for transition in iteration 37
Cluster tracking complete!
21 Cluster track complete for transition in iteration 38
Cluster tracking complete!
22 Cluster track complete for transition in iteration 46
Cluster tracking complete!
23 Cluster track complete for transition in iteration 48
Cluster tracking complete!
24 Cluster track complete for transition in iteration 50
Cluster tracking complete!
25 Cluster track complete for transition in iteration 51
Cluster tracking complete!
26 Cluster track complete for transition in iteration 51
Cluster tracking complete!
27 Cluster track complete for transition in iteration 51
Cluster tracking complete!
28 Cluster track complete for transition in iteration 54
Cluster tracking complete!
29 Cluster track complete for transition in iteration 59
Cluster tracking complete!
30 Cluster track complete for transition in iteration 61
Cluster tracking complete!
31 Cluster track complete for transition in iteration 64

#### Use node communities data  
- This stores iteration number as 'level 0' index
- Contains 5000x426 dataframe if you index with iteration number eg. df.loc[0]
- If iteration has more than 1 transition, use df.loc[0].iloc[5000:] to extract node community for second transition and so on

In [3]:
df_nc = nc_ext.data_read_bz2("raw/PERI/nc_200.bz2")

In [4]:
df_nc.loc[195]

,0,1,2,3,4,5,6,7,8,9,...,416,417,418,419,420,421,422,423,424,425
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,8.0,0.0,8.0,0.0,0.0,0.0,8.0,8.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4996,8.0,0.0,8.0,0.0,0.0,0.0,8.0,8.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4997,8.0,0.0,8.0,0.0,0.0,0.0,8.0,8.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4998,8.0,0.0,8.0,0.0,0.0,0.0,8.0,8.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4999,8.0,0.0,8.0,0.0,0.0,0.0,8.0,8.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
analyse.compute_main_cluster(df_nc.loc[51].iloc[0:5000])

1

In [10]:
df_nc.loc[2].iloc[0:5000]

        0    1      2      3      4    5    ...    420    421  422  423  424  425
0       0.0  0.0    0.0    0.0    0.0  0.0  ...    0.0   14.0  0.0  0.0  0.0  0.0
1       0.0  0.0    0.0    0.0    0.0  0.0  ...    0.0   22.0  0.0  0.0  0.0  0.0
2       0.0  0.0    0.0    0.0    0.0  0.0  ...    0.0   22.0  0.0  0.0  0.0  0.0
3       0.0  0.0    0.0    0.0    0.0  0.0  ...    0.0   23.0  0.0  0.0  0.0  0.0
4       0.0  0.0    0.0    0.0    0.0  0.0  ...    0.0   17.0  0.0  0.0  0.0  0.0
...     ...  ...    ...    ...    ...  ...  ...    ...    ...  ...  ...  ...  ...
4995  151.0  0.0  151.0  151.0  151.0  0.0  ...  151.0  151.0  0.0  0.0  0.0  0.0
4996  151.0  0.0  151.0  151.0  151.0  0.0  ...  151.0  151.0  0.0  0.0  0.0  0.0
4997  151.0  0.0  151.0  151.0  151.0  0.0  ...  151.0  151.0  0.0  0.0  0.0  0.0
4998  151.0  0.0  151.0  151.0  151.0  0.0  ...  151.0  151.0  0.0  0.0  0.0  0.0
4999  151.0  0.0  151.0  151.0  151.0  0.0  ...  151.0  151.0  0.0  0.0  0.0  0.0

[5000 rows x 426 columns]

In [11]:
df_nc.loc[2].iloc[5000:10000]

       0    1    2     3    4    5     6    ...  419  420   421  422  423  424  425
0      0.0  0.0  0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   0.0  0.0  0.0  3.0  0.0
1      0.0  0.0  0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   0.0  0.0  0.0  3.0  0.0
2      0.0  0.0  0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   0.0  0.0  0.0  3.0  0.0
3      0.0  0.0  0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   0.0  0.0  0.0  3.0  0.0
4      0.0  0.0  0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   0.0  0.0  0.0  3.0  0.0
...    ...  ...  ...   ...  ...  ...   ...  ...  ...  ...   ...  ...  ...  ...  ...
4995  70.0  0.0  0.0  70.0  0.0  0.0  70.0  ...  0.0  0.0  70.0  0.0  0.0  0.0  0.0
4996  70.0  0.0  0.0  70.0  0.0  0.0  70.0  ...  0.0  0.0  70.0  0.0  0.0  0.0  0.0
4997  70.0  0.0  0.0  70.0  0.0  0.0  70.0  ...  0.0  0.0  70.0  0.0  0.0  0.0  0.0
4998  70.0  0.0  0.0  70.0  0.0  0.0  70.0  ...  0.0  0.0  70.0  0.0  0.0  0.0  0.0
4999  70.0  0.0  0.0  70.0  0.0  0.0  70.0  ...  0.0  0.0  70.0  0.0  0.0  0.0  0.0

[5000 rows x 426 columns]