# Extract node community using local order data  
1. Extract node communities data

In [1]:
from tes.data_ingestion import DataRead

Create object to read data

In [2]:
nc_ext=DataRead()

Store local order data in dataframe

In [3]:
df=nc_ext.data_read_bz2('l20_fn.bz2')

#### 1. Extract node communities data

In [4]:
threshold = 0.3
nc_ext.ext_node_community(df,threshold,'nc3_fn.bz2')

D:\srg_tES\srg-tes-epilepsy-models\data\connectivity_matrix\mb_communities.npz already exists
DataUtils initialized
Cluster tracking complete!
1 Cluster track complete for transition 0
Cluster tracking complete!
2 Cluster track complete for transition 2
Cluster tracking complete!
3 Cluster track complete for transition 2
Stored node communities data in data folder

#### Use node communities data  
- This stores iteration number as 'level 0' index
- Contains 5000x426 dataframe if you index with iteration number eg. df.loc[0]
- If iteration has more than 1 transition, use df.loc[0].iloc[5000:] to extract node community for first transition and so on

In [6]:
df_nc =nc_ext.data_read_bz2('nc3_fn.bz2')

In [9]:
df_nc.loc[0]

       0     1     2     3     4     5    ...  420   421  422  423   424   425
0      0.0   0.0   0.0   0.0   0.0   0.0  ...  0.0   0.0  0.0  0.0   0.0   0.0
1      0.0   0.0   0.0   0.0   0.0   0.0  ...  0.0   0.0  0.0  0.0   0.0   0.0
2      0.0   0.0   0.0   0.0   0.0   0.0  ...  0.0   0.0  0.0  0.0   0.0   0.0
3      0.0   0.0   0.0   0.0   0.0   0.0  ...  0.0   0.0  0.0  0.0   0.0   0.0
4      0.0   0.0   0.0   0.0   0.0   0.0  ...  0.0   0.0  0.0  0.0   0.0   0.0
...    ...   ...   ...   ...   ...   ...  ...  ...   ...  ...  ...   ...   ...
4995  76.0  76.0  76.0  76.0  76.0  76.0  ...  0.0  76.0  0.0  0.0  76.0  76.0
4996  76.0  76.0  76.0  76.0  76.0  76.0  ...  0.0  76.0  0.0  0.0  76.0  76.0
4997  76.0  76.0  76.0  76.0  76.0  76.0  ...  0.0  76.0  0.0  0.0  76.0  76.0
4998  76.0  76.0  76.0  76.0  76.0  76.0  ...  0.0  76.0  0.0  0.0  76.0  76.0
4999  76.0  76.0  76.0  76.0  76.0  76.0  ...  0.0  76.0  0.0  0.0  76.0  76.0

[5000 rows x 426 columns]

In [10]:
df_nc.loc[2].iloc[0:5000]

        0    1      2      3      4    5    ...    420    421  422  423  424  425
0       0.0  0.0    0.0    0.0    0.0  0.0  ...    0.0   14.0  0.0  0.0  0.0  0.0
1       0.0  0.0    0.0    0.0    0.0  0.0  ...    0.0   22.0  0.0  0.0  0.0  0.0
2       0.0  0.0    0.0    0.0    0.0  0.0  ...    0.0   22.0  0.0  0.0  0.0  0.0
3       0.0  0.0    0.0    0.0    0.0  0.0  ...    0.0   23.0  0.0  0.0  0.0  0.0
4       0.0  0.0    0.0    0.0    0.0  0.0  ...    0.0   17.0  0.0  0.0  0.0  0.0
...     ...  ...    ...    ...    ...  ...  ...    ...    ...  ...  ...  ...  ...
4995  151.0  0.0  151.0  151.0  151.0  0.0  ...  151.0  151.0  0.0  0.0  0.0  0.0
4996  151.0  0.0  151.0  151.0  151.0  0.0  ...  151.0  151.0  0.0  0.0  0.0  0.0
4997  151.0  0.0  151.0  151.0  151.0  0.0  ...  151.0  151.0  0.0  0.0  0.0  0.0
4998  151.0  0.0  151.0  151.0  151.0  0.0  ...  151.0  151.0  0.0  0.0  0.0  0.0
4999  151.0  0.0  151.0  151.0  151.0  0.0  ...  151.0  151.0  0.0  0.0  0.0  0.0

[5000 rows x 426 columns]

In [11]:
df_nc.loc[2].iloc[5000:10000]

       0    1    2     3    4    5     6    ...  419  420   421  422  423  424  425
0      0.0  0.0  0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   0.0  0.0  0.0  3.0  0.0
1      0.0  0.0  0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   0.0  0.0  0.0  3.0  0.0
2      0.0  0.0  0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   0.0  0.0  0.0  3.0  0.0
3      0.0  0.0  0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   0.0  0.0  0.0  3.0  0.0
4      0.0  0.0  0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   0.0  0.0  0.0  3.0  0.0
...    ...  ...  ...   ...  ...  ...   ...  ...  ...  ...   ...  ...  ...  ...  ...
4995  70.0  0.0  0.0  70.0  0.0  0.0  70.0  ...  0.0  0.0  70.0  0.0  0.0  0.0  0.0
4996  70.0  0.0  0.0  70.0  0.0  0.0  70.0  ...  0.0  0.0  70.0  0.0  0.0  0.0  0.0
4997  70.0  0.0  0.0  70.0  0.0  0.0  70.0  ...  0.0  0.0  70.0  0.0  0.0  0.0  0.0
4998  70.0  0.0  0.0  70.0  0.0  0.0  70.0  ...  0.0  0.0  70.0  0.0  0.0  0.0  0.0
4999  70.0  0.0  0.0  70.0  0.0  0.0  70.0  ...  0.0  0.0  70.0  0.0  0.0  0.0  0.0

[5000 rows x 426 columns]